defaults: &defaults
  working_directory: ~/working_directory
  steps:
    - checkout
    - run: node --version
    - run: npm --version
    - restore_cache:
        key: v1-npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install
    - save_cache:
        key: v1-npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run: npm run circleci

env_vars: &env_vars
  environment:
    NO_WATCH_TESTS: 1

version: 2
jobs:
  build-node6:
    <<: *defaults
    docker:
      - image: node:6
        <<: *env_vars
  build-node8:
    <<: *defaults
    docker:
      - image: node:8
        <<: *env_vars
workflows:
  version: 2
  build:
    jobs:
      - build-node6
      - build-node8
